### ISSUE TITLE
[Feature]: Convert hash history to web based history

### ISSUE THREAD

**Issue by seriouslysean** [cuttle-cards/cuttle#675] opened 2023-10-12 14:43 UTC
### Feature Summary

Convert hash history to web based history

### Detailed Description

It's preferable to use `/path/to/page` rather than `/#/path/to/page` and will make a good basis for updating the meta information and finally improving SEO, along with a sitemap.

**Comment by itsalaidbacklife** [comment] 2024-03-19 14:51
Closing as duplicate of #580

**Closed as completed by itsalaidbacklife** 2024-03-19 14:51 UTC
Labels: enhancement, version-minor, backend, frontend
